#pragma once
#include <string>

enum TokenType {
    TOK_EOF,
    TOK_NUMBER, TOK_STRING, TOK_IDENT,
    TOK_PLUS, TOK_MINUS, TOK_STAR, TOK_SLASH,
    TOK_LPAREN, TOK_RPAREN, TOK_LBRACE, TOK_RBRACE,
    TOK_LBRACK, TOK_RBRACK,
    TOK_COMMA, TOK_DOT, TOK_COLON, TOK_DCOLON,
    TOK_ASSIGN, TOK_EQ, TOK_STRICT_EQ, TOK_NEQ, TOK_LT, TOK_GT, TOK_LTE, TOK_GTE,
    TOK_FN, TOK_RETURN, TOK_TRUE, TOK_FALSE,
    TOK_IF, TOK_EL, TOK_FOR, TOK_WHILE,
    TOK_YAP, TOK_ARROW, TOK_PLUSPLUS,
    TOK_TIME_START, TOK_TIME_END, TOK_FIXED,
    TOK_TRY, TOK_CATCH, TOK_IN,
    TOK_AND, TOK_OR
};

struct Token {
    TokenType type;
    std::string value;
    int line, col;
};